### ISSUE TITLE
(wild) Idea: continuous mode

### ISSUE THREAD

**Issue by teranex** [joonty/vdebug#19] opened 2012-11-06 10:14 UTC
Just a wild (maybe useless) idea: would it be possible to add a 'continuous mode'? This would be a mode where VDebug would automatically restart to listen (with a large enough timeout) after a request has ended. That would allow one to setup some breakpoints, start the debugger in Vim, and click through the php project until the page is reached which will trigger the breakpoints.
Now most of the times I set my breakpoints, start clicking around to reach the correct page, and before the final click need to remember to, at that moment, start the debugger in vim before continuing.

(obviously this is most useful if you have configured XDebug to automatically open a debug session on the server)

**Comment by Dudemullet** [comment] 2015-12-07 22:31
Hi, might I suggest closing this ? I thought this mode didn't exist yet (since the issue is still open) and just stumbled upon on it in the documentation by luck, just like you said here @joonty.

>I think this problem (blocking Vim UI while listening) is not related to the current issue (continuous mode) and can be moved to another issue.

Anyone reading this that cares for the solution, the option is

`let g:vdebug_options['continuous_mode'] = 1`

which you might have to combo with:

```
let g:vdebug_options['break_on_open'] = 0
let g:vdebug_options['continuous_mode'] = 1
```


Thanks by the way, this mode is working great :+1:

**Comment by joonty** [comment] 2015-12-08 07:28
Hi @Dudemullet, thanks for raising this.

While there is a continuous mode in version 1, it doesn't quite fit the brief of the original request, as it blocks the user after a debugging session has ended, until the next one starts. In version 2 I have it working so that it doesn't block, but there are still some things that need to be done to get it production ready. So I said it's not related in a previous comment, but it sort of is related! :P

The reason I left this open was so I could notify everyone in the thread when I get version 2 out. That will happen at some point, promise!

**Closed** 2018-03-10 11:07 UTC
Labels: enhancement

**Comment by baptx** [comment] 2018-03-12 18:14
Has continuous mode been added to the new version? (I saw the issue was closed)

**Comment by BlackIkeEagle** [comment] 2019-11-04 18:14
@baptx yes, when the previous request is finished and another hits vdebug it will start debugging immediatly
