### ISSUE TITLE
Not work in Neovim

### ISSUE THREAD

**Issue by drwx** [joonty/vdebug#188] opened 2014-10-23 09:33 UTC
Hi joonty,

When I start debug php in neovim, there are some errors:

  File "~/.nvim/neobundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "~/.nvim/neobundle/vdebug/plugin/python/vdebug/runner.py", line 160, in run
    self.open()
  File "~/.nvim/neobundle/vdebug/plugin/python/vdebug/runner.py", line 47, in open
    self.ui.open()
  File "~/.nvim/neobundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 75, in open
    raise e
AttributeError: **delitem**

so How to solve these errors?

Thanks

**Comment by adambiggs** [comment] 2015-03-13 22:13
@drwx you need to install the `neovim` python library: `$ pip install neovim`

**Comment by mike3run** [comment] 2017-01-02 13:05
Im running on those same issues even though I have python neovim installed :/

**Comment by BlackIkeEagle** [comment] 2017-01-02 14:18
I can confirm vdebug needs some work to work nicely in neovim

**Comment by BlackIkeEagle** [comment] 2017-01-02 14:18
For now if you want to use vdebug use vim

**Comment by mike3run** [comment] 2017-01-02 19:49
True i can confirm that with my exact same settings as neovim vdebug works just fine, guess i'll use that for the project im currently working.

Thanks a lot for the feedback appreciate it, @BlackIkeEagle

**Comment by Taluu** [comment] 2017-01-27 10:49
I can confirm that vDebug works just fine with neovim

**Comment by BlackIkeEagle** [comment] 2017-01-27 13:48
@Taluu You mean it works fine now in the latest versions of neovim? It did not work completely fine with pre 0.1.5 versions I have tested

**Comment by Taluu** [comment] 2017-01-27 13:54
It seems I am using `0.2.0-dev`, but at least it works fine with it

**Comment by BlackIkeEagle** [comment] 2017-01-27 14:19
@Taluu that's great news

**Comment by Taluu** [comment] 2017-01-29 22:40
It works also fine with 0.1.7. :}

**Comment by beatscode** [comment] 2017-01-31 13:57
I'm running nvim 0.1.7 installed via homebrew on mac os sierra 10.12.12
I installed neovim via pip as well (0.1.9)

Here are my vdebug settings:
````
let g:vdebug_options["port"] = 9000
let g:vdebug_options["server"] = '192.168.1.151'
let g:vdebug_options["ide_key"] = 'xyz'
````
I get the following error after setting a breakpoint and refreshing a page in my application
![image](https://cloud.githubusercontent.com/assets/1777648/22467495/e2daab98-e792-11e6-9d89-f5135d49623d.png)

What should I attribute this error message to?

**Comment by still-dreaming-1** [comment] 2017-03-16 01:03
You will still need to get python 2 support working in Neovim: https://neovim.io/doc/user/provider.html#provider-python
Here is a quick summary. While Neovim is running, see if you already have python 2 support by running `:echo has('python')`. You will see 0 (meaning not enabled) or 1 (meaning enabled) echoed at the bottom left. If it is a 1, you should be done. Otherwise you will need to make sure python 2 itself is already installed. From the terminal type `pip2` to see if you have python 2. If you don't then install python 2 however you do that on your system. Then move on to adding python 2 support for Neovim by running this from the terminal: `pip2 install --user --upgrade neovim`. That way is recommended over sudo so you don't mess up your distribution later on.

**Comment by lucc** [comment] 2017-05-14 07:13
I think this can be closed. I am also using vdebug (master) with Neovim 0.1.7 and 0.2 successfully.

**Comment by BlackIkeEagle** [comment] 2017-05-14 15:28
Closing because confirmed working

**Closed by BlackIkeEagle** 2017-05-14 15:28 UTC

**Comment by mortona42** [comment] 2017-09-04 04:40
I was unable to get vdebug to work with vim in Debian 9. However, I have neovim working with still-dtreaming-1's instructions above. Can we put this in the readme? I think a lot more people will encounter this with newer linux installs.
