### ISSUE TITLE
VIM UI hangs when Vdebug receives a connection

### ISSUE THREAD

**Issue by JohnMaguire** [joonty/vdebug#218] opened 2015-07-01 19:08 UTC
First of all, thank you for the plugin. Unfortunately, I am experiencing some issues with the vim UI hanging, and not re-drawing until the debugger stops.
1. I open vim and then press F5.
2. The console tells me it's waiting for a connection. C-c causes this to stop properly. However, if I don't C-c...
3. I start a command-line PHP process with Xdebug, which connects back to Vdebug.
4. Vdebug starts the debugger.
5. I no longer am able to interact with the UI of vim at all.

I have noticed that if I have a breakpoint on startup, the vim UI will continue to function properly, until I hit F5 again, with no further breakpoints to hit.

Is this expected behavior? I can't even seem to find a way to stop Vdebug while it's looping, short of killing the Xdebug client.

`$ cat ~/vdebug.log`  

```
- [Info] {Wed 01 2015 14:49:39} Found connection from ('10.66.5.23', 52035)
- [Debug] {Wed 01 2015 14:49:39} Command: context_names -i 1
- [Debug] {Wed 01 2015 14:49:39} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="1"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context><context name="User defined constants" id="2"></context></response>
- [Debug] {Wed 01 2015 14:49:39} Available context names: {0: 'Locals', 1: 'Superglobals', 2: 'User defined constants'}
- [Debug] {Wed 01 2015 14:49:39} Command: run -i 2
- [Debug] {Wed 01 2015 14:49:47} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="2" status="stopping" reason="ok"></response>
- [Info] {Wed 01 2015 14:49:47} Debugging session has ended
- [Info] {Wed 01 2015 14:49:47} Closing the connection
- [Debug] {Wed 01 2015 14:49:47} Closing the socket
```

`$ vim --version`  

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  5 2015 00:13:04)
MacOS X (unix) version
Included patches: 1-488
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
```

**Comment by cincodenada** [comment] 2015-07-21 18:31
I don't know that I would classify this as *intended* behavior, but I was able to reproduce it.  It seems more like an unexpected use case.  Just out of curiosity, what is your use case for using Vim while the program being debugged is running?

And to confirm, in my tests, Vim also returns to responding when I kill the program being debugged, is that the case on your end as well?

What's happening here, I believe, is that Vdebug tells the debugger to run, and waits for a response - which doesn't come until either a breakpoint is hit, or the debugging session ends.  That wait is blocking, so nothing happens while we're waiting for the response.  We may well be able to make that non-blocking, much like the initial connect process.  I'll look into it.

**Comment by JohnMaguire** [comment] 2015-07-21 18:37
Yes it sounds like you've reproduced it  correctly. At minimum, I expected
to be able to kill the debug session (I.e. Tell vim to stop blocking on
that socket), but every other editor with integrated debugging I've used
has allowed me to browse around my files while I'm debugging (use case
being to verify that related code is setup to work with the values you're
seeing while debugging, for example.)

But honestly, I think you make a good point that if you're debugging and
waiting for a breakpoint to hit, you're probably not bouncing around files.
I'd still think the option to kill the debug session from the client (well,
vdebug server) side makes a lot of sense.

**Comment by JohnMaguire** [comment] 2015-07-21 18:38
And also, if you have no breakpoints set, hit start debugging and vim just
freezes on you, that kinda sucks. :(

In any case, thanks a lot for your help!

**Comment by mispencer** [comment] 2015-07-21 18:43
https://github.com/joonty/vdebug/pull/194 might be of interest to you.

**Comment by JohnMaguire** [comment] 2015-07-21 18:47
Thanks! #194 is exactly what I'm looking for.

**Comment by cincodenada** [comment] 2015-07-21 19:08
Ah, I had seen #194, but didn't make the connection to this issue.  But looking through it, it does look to be along the lines of what I was imagining a solution would look like.  Thanks for chiming in, @mispencer!

**Comment by BlackIkeEagle** [comment] 2017-03-24 07:21
@JohnMaguire this issue is fixed in the v2 branch you can start testing it in v2-integration

**Closed by BlackIkeEagle** 2017-03-24 07:21 UTC
Labels: enhancement
