### ISSUE TITLE
vdebug does  not do anything on pressing F5 Ubuntu 16.04 LTS. 

### ISSUE THREAD

**Issue by Mofiqul** [joonty/vdebug#265] opened 2017-02-01 06:05 UTC
Hi I want to use vdebug to debug my python and php program, i have installed xdebug and configured it as mentioned in your instruction but it does not do anything on pressing F5. if i run :python debugger.run() the message is Sorry, the command is not available in this version. Only i can get is the help text file if i run :help vdebug . I am using SPF13 vim and my vim version is 7.4. please help

**Comment by BlackIkeEagle** [comment] 2017-02-01 08:13
@Mofiqul Is your ubuntu vim built with python2 enabled?

~~~
$ vim --version | grep python
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
~~~

**Comment by Mofiqul** [comment] 2017-02-02 11:54
Sorry for late replay
the output was like this :
+cryptv          +linebreak       -python          +vreplace 
+cscope          +lispindent      +python3         +wildignore
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-i386-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm


is that a python2 issue?

**Comment by BlackIkeEagle** [comment] 2017-02-02 12:04
you need +python for vdebug to work, +python3 is not supported yet

**Comment by Mofiqul** [comment] 2017-02-02 12:06
how i do that?

**Comment by BlackIkeEagle** [comment] 2017-02-02 12:22
install vim with python2 support

ubuntu does not provide packages with python3 and python2 support together I think

~~~ sh
$ apt-get install vim-nox-py2
or
$ apt-get install vim-gtk3-py2
or
$ apt-get install vim-gtk-py2
~~~

**Comment by Garethp** [comment] 2017-02-24 17:04
Hey. I'm running Vim8 which compiled with Python3 (And I had some trouble compiling it with Python2 for some reason) so I'm currently working on a fork to bring in Python3 support. It's found [here](https://github.com/Garethp/vdebug/pull/1). Once I can make my branch compatible with both Python2 and Python3, I'll make a PR against your Repo, but for now this seems to work for me.

Are there any specific things I should try to make sure that I've got things working 100%? So far debugging and stepping through works without problems, as well as exception handling

**Comment by BlackIkeEagle** [comment] 2017-02-24 18:54
@Garethp Thanks for putting in the effort of porting to python3. I don't think there is a need to maintain compatibility with python2. For people using an older version of vim with only python2 available we should just provide a marked version where the break starts.

Something like 1.5.x will be the last version supporting python2 from 1.6 on python3 will be required

**Comment by zjhxmjl** [comment] 2017-03-04 13:04
@Mofiqul do you solve this problem?

**Comment by zjhxmjl** [comment] 2017-03-04 15:30
@BlackIkeEagle i only get python not "python/dyn ",are there any packages not installed?system: ubuntu 14.01
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore

**Comment by Mofiqul** [comment] 2017-03-06 10:58
No..I was not able to solve the problem even after i installed python2
support. there python2 support now but still does not start when i press F5
.
I wish i could use your vdebug.

**Comment by cincodenada** [comment] 2017-03-06 18:48
@Mofiqul To be clear, your `vim --version | grep python` now includes a "+python" (not just "+python3") entry?

If that's the case, what happens now when you run `:python debugger.run()`? Do you get any output in the debug log [after you enable it](https://github.com/joonty/vdebug#debugging)?

**Comment by BlackIkeEagle** [comment] 2017-03-24 06:54
@Mofiqul there is PR#271 which brings python3 support, I hope your problem is fixed with python3 support, it will be released with v2.0

**Closed by BlackIkeEagle** 2017-03-24 06:54 UTC

**Comment by kenpeter** [comment] 2017-06-19 11:53
Using this I am able to make python 2 working with vim: https://askubuntu.com/questions/775059/vim-python-support-on-ubuntu-16-04. if do a vim --version | grep python. It output +python. The issue is that when I do :python debugger.run(). and load the webpage. Nothing happens inside the vim. normally it will go into debugging in vim for older version.

**Comment by BlackIkeEagle** [comment] 2017-06-19 14:40
@kenpeter if you have php5.6 are you using a ppa? like ondrej's php ppa?

you should be able to install php-xdebug which contains everything for php 5.6, 7.0 and 7.1 at the time of writing

**Comment by kenpeter** [comment] 2017-06-20 01:12
I have these:

/etc/apt/sources.list.d/pi-rho-ubuntu-dev-xenial.list:deb http://ppa.launchpad.net/pi-rho/dev/ubuntu xenial main

/etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list:deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main

I have this in my ubuntubox:
php-xdebug is already the newest version (2.5.4-1~ubuntu16.04.1+deb.sury.org+1).

Press F5, it says:
Waiting for a connection (Ctrl-C to cancel, this message will self-destruct in  20  seconds...)
reload page nothing happens.

I have this in php.ini

```
[Xdebug]
zend_extension=/usr/lib/php/20160303/xdebug.so
xdebug.remote_enable=on
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=localhost
xdebug.remote_port=9000
```

Also try these:

```
:VdebugOpt debug_file ~/vdebug.log
:VdebugOpt debug_file_level 2
```
The press F5, again it is just listening, even after reload page

**Comment by baptx** [comment] 2017-12-13 12:59
The solution for me was to install the package `vim-nox-py2` and to select Python 2 with command `sudo update-alternatives --config vim` https://askubuntu.com/questions/775059/vim-python-support-on-ubuntu-16-04#comment1223693_775060
