### ISSUE TITLE
Can't remove / set breakpoints if vdebug is not running after being run once

### ISSUE THREAD

**Issue by Taluu** [joonty/vdebug#319] opened 2018-01-29 12:15 UTC
Setting some breakpoints and removing them is easy, before running vdebug (through `F5`)... but once it launched and stopped, we have the message "vdebug is not running".

I think this is due to the async listening, but I'm not too sure ?

I'm using nvim 0.2 on the v2-integration branch.

**Comment by BlackIkeEagle** [comment] 2018-03-01 19:57
Thanks for reporting thisone, the issue is now resolved in v2-integration

**Closed by BlackIkeEagle** 2018-03-01 19:57 UTC
